+*In[35]:*+
[source, ipython3]
----
import pandas as pd
import numpy as np

df = pd.read_excel (r'/Users/jiang/Library/Mobile Documents/com~apple~CloudDocs/Desktop/OneDrive - HKUST Connect/Research/Smart City/Data/Data_0328.xlsx',sheet_name='Sheet1',header=0, names = None)

----


+*In[36]:*+
[source, ipython3]
----
print(df.head())
----


+*Out[36]:*+
----
   c1  order_number                                         ä¸­æ ‡æ ‡é¢˜    industry  \
0   1             1                                     å…µå›¢RAè®¤è¯ç³»ç»Ÿ         NaN   
1   2             2             æ´›é˜³é«˜æ–°åŒºå‘å±•æ€§è¯„ä»·åŠæ•™ä¸å­¦åˆ†æåº”ç”¨ç³»ç»Ÿé¡¹ç›®å•ä¸€æ¥æºæˆäº¤ç»“æœå…¬å‘Š         NaN   
2   3             3  éƒ‘å·é«˜æ–°æŠ€æœ¯äº§ä¸šå¼€å‘åŒº2016-2018å¹´åº¦è¡Œæ”¿äº‹ä¸šå•ä½åè®®ä¾›è´§åŠå®šç‚¹æœåŠ¡é¡¹ç›®ä¸­æ ‡å…¬å‘Š  Government   
3   4             4                     å®‰é˜³é«˜æ–°åŒºç¬¬ä¸‰å°å­¦LEDå±ã€éŸ³å“ç³»ç»Ÿé‡‡è´­é¡¹ç›®äºŒæ¬¡   Education   
4   5             5                  ä¸­ç»ç¤¾æ§è‚¡æœ‰é™å…¬å¸é‡‘èä¿¡æ¯å¹³å°ä¸€æœŸé¡¹ç›®ç›‘ç†å­é¡¹ä¸­æ ‡å…¬å‘Š         NaN   

   å…³é”®è¯   åœ°åŒº   å¸‚2   å¸‚1                  é‡‡è´­å•ä½ organization    å¹´ä»½  \
0   ç®—æ³•  NaN  NaN  NaN      æ–°ç–†ç”Ÿäº§å»ºè®¾å…µå›¢ä¿¡æ¯æŠ€æœ¯æœåŠ¡ä¸­å¿ƒ          NaN  2017   
1   æˆæƒ  NaN  NaN  æ´›é˜³å¸‚  æ´›é˜³é«˜æ–°æŠ€æœ¯äº§ä¸šå¼€å‘åŒºæ”¿åºœé‡‡è´­ç®¡ç†åŠå…¬å®¤          NaN  2016   
2   æˆæƒ  NaN  NaN  éƒ‘å·å¸‚    éƒ‘å·é«˜æ–°æŠ€æœ¯äº§ä¸šå¼€å‘åŒºæ”¿åºœé‡‡è´­åŠå…¬å®¤          NaN  2016   
3   æˆæƒ  NaN  NaN  å®‰é˜³å¸‚      å®‰é˜³é«˜æ–°æŠ€æœ¯äº§ä¸šå¼€å‘åŒºç¤¾ä¼šäº‹ä¸šå±€          NaN  2016   
4  ä¿¡æ¯åŒ–   åŒ—äº¬  NaN  NaN             ä¸­ç»ç¤¾æ§è‚¡æœ‰é™å…¬å¸          NaN  2016   

                                                link             ä»£ç†å…¬å¸  \
0  http://www.ccgp.gov.cn/cggg/dfgg/zbgg/201708/t...  æ–°ç–†å¤©ç‘æ–°ç§‘æ‹›æŠ•æ ‡æœ‰é™è´£ä»»å…¬å¸   
1  http://www.ccgp.gov.cn/cggg/dfgg/zbgg/201608/t...   æ²³å—è¯šå®‰å·¥ç¨‹ç®¡ç†å’¨è¯¢æœ‰é™å…¬å¸   
2  http://www.ccgp.gov.cn/cggg/dfgg/zbgg/201605/t...  æ²³å—çœè‡³è¯šæ‹›æ ‡é‡‡è´­æœåŠ¡æœ‰é™å…¬å¸   
3  http://www.ccgp.gov.cn/cggg/dfgg/zbgg/201603/t...   é«˜è¾¾å»ºè®¾ç®¡ç†å‘å±•æœ‰é™è´£ä»»å…¬å¸   
4  http://www.ccgp.gov.cn/cggg/zygg/zbgg/201602/t...     äº”çŸ¿å›½é™…æ‹›æ ‡æœ‰é™è´£ä»»å…¬å¸   

                æ—¥æœŸ  ä¸­æ ‡é‡‘é¢        ä¸­æ ‡å•ä½  
0  2017/8/25 17:07   NaN         NaN  
1  2016/8/10 12:20   NaN  ç§‘å¤§è®¯é£è‚¡ä»½æœ‰é™å…¬å¸  
2   2016/5/6 10:17   NaN         NaN  
3   2016/3/2 14:36   NaN         NaN  
4   2016/2/2 15:19   NaN         NaN  
----


+*In[37]:*+
[source, ipython3]
----
print(df.columns.ravel())
----


+*Out[37]:*+
----
['c1' 'order_number' 'ä¸­æ ‡æ ‡é¢˜' 'industry' 'å…³é”®è¯' 'åœ°åŒº' 'å¸‚2' 'å¸‚1' 'é‡‡è´­å•ä½'
 'organization' 'å¹´ä»½' 'link' 'ä»£ç†å…¬å¸' 'æ—¥æœŸ' 'ä¸­æ ‡é‡‘é¢' 'ä¸­æ ‡å•ä½']
----


+*In[16]:*+
[source, ipython3]
----
pip install addressparser
----


+*Out[16]:*+
----
Collecting addressparser
  Downloading addressparser-0.1.8.tar.gz (103 kB)
[K     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 103 kB 353 kB/s eta 0:00:01
[?25hCollecting jieba
  Downloading jieba-0.42.1.tar.gz (19.2 MB)
[K     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 19.2 MB 361 kB/s eta 0:00:01
[?25hRequirement already satisfied: pandas in ./opt/anaconda3/lib/python3.8/site-packages (from addressparser) (1.1.3)
Requirement already satisfied: pytz>=2017.2 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas->addressparser) (2020.1)
Requirement already satisfied: numpy>=1.15.4 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas->addressparser) (1.19.2)
Requirement already satisfied: python-dateutil>=2.7.3 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas->addressparser) (2.8.1)
Requirement already satisfied: six>=1.5 in ./opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas->addressparser) (1.15.0)
Building wheels for collected packages: addressparser, jieba
  Building wheel for addressparser (setup.py) ... [?25ldone
[?25h  Created wheel for addressparser: filename=addressparser-0.1.8-py3-none-any.whl size=105771 sha256=bc1f594f7250c7541181488d768625f5d3c5d05b37633b3a79bff3fe778f0524
  Stored in directory: /Users/jiang/Library/Caches/pip/wheels/15/55/b3/cc70812a1e56245798ae19989e6bf79a54763ab061aeb72ab9
  Building wheel for jieba (setup.py) ... [?25ldone
[?25h  Created wheel for jieba: filename=jieba-0.42.1-py3-none-any.whl size=19314478 sha256=d160d705a077b53d62b7c8fa38e38ca7bc28f570d295ab4478f8064e9c89b0eb
  Stored in directory: /Users/jiang/Library/Caches/pip/wheels/ca/38/d8/dfdfe73bec1d12026b30cb7ce8da650f3f0ea2cf155ea018ae
Successfully built addressparser jieba
Installing collected packages: jieba, addressparser
Successfully installed addressparser-0.1.8 jieba-0.42.1
Note: you may need to restart the kernel to use updated packages.
----


+*In[20]:*+
[source, ipython3]
----
import addressparser
----


+*In[27]:*+
[source, ipython3]
----
type(df["ä¸­æ ‡æ ‡é¢˜"])
----


+*Out[27]:*+
----pandas.core.series.Series----


+*In[31]:*+
[source, ipython3]
----
location_str = df["ä¸­æ ‡æ ‡é¢˜"]
df1 = addressparser.transform(location_str)
print(df1)
----


+*Out[31]:*+
----

    ---------------------------------------------------------------------------

    KeyError                                  Traceback (most recent call last)

    ~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
       2894             try:
    -> 2895                 return self._engine.get_loc(casted_key)
       2896             except KeyError as err:


    pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()


    pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()


    pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()


    pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()


    KeyError: 'ä¸­æ ‡æ ‡é¢˜,ä¸­æ ‡å•ä½'

    
    The above exception was the direct cause of the following exception:


    KeyError                                  Traceback (most recent call last)

    <ipython-input-31-54b1ea01689f> in <module>
    ----> 1 location_str = df["ä¸­æ ‡æ ‡é¢˜,ä¸­æ ‡å•ä½"]
          2 df1 = addressparser.transform(location_str)
          3 print(df1)


    ~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
       2900             if self.columns.nlevels > 1:
       2901                 return self._getitem_multilevel(key)
    -> 2902             indexer = self.columns.get_loc(key)
       2903             if is_integer(indexer):
       2904                 indexer = [indexer]


    ~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
       2895                 return self._engine.get_loc(casted_key)
       2896             except KeyError as err:
    -> 2897                 raise KeyError(key) from err
       2898 
       2899         if tolerance is not None:


    KeyError: 'ä¸­æ ‡æ ‡é¢˜,ä¸­æ ‡å•ä½'

----


+*In[30]:*+
[source, ipython3]
----
# saving the dataframe
df1.to_excel(r'/Users/jiang/Library/Mobile Documents/com~apple~CloudDocs/Desktop/OneDrive - HKUST Connect/Research/Smart City/Data/Data_0328.xlsx', index=False)
----


+*In[32]:*+
[source, ipython3]
----
location_str = df["ä¸­æ ‡å•ä½"]
df2 = addressparser.transform(location_str)
print(df2)
----


+*Out[32]:*+
----
         çœ    å¸‚ åŒº                 åœ°å€
0                                NaN
1                         ç§‘å¤§è®¯é£è‚¡ä»½æœ‰é™å…¬å¸
2                                NaN
3                                NaN
4                                NaN
...    ...  ... ..               ...
56080  åŒ—äº¬å¸‚  åŒ—äº¬å¸‚     ç››ä¸–ç¬”ç‰¹ï¼ˆåŒ—äº¬ï¼‰æ¨¡å‹è®¾è®¡æœ‰é™å…¬å¸
56081  ä¸Šæµ·å¸‚  ä¸Šæµ·å¸‚         æƒ è¯šç§‘æ•™å™¨æ¢°è‚¡ä»½æœ‰é™å…¬å¸
56082  æ²³å—çœ                  é£é€Ÿç§‘æŠ€æœ‰é™å…¬å¸
56083  æ²³å—çœ                è±«ç«‹ç”µå­ç§‘æŠ€æœ‰é™å…¬å¸
56084  ç¦å»ºçœ                æ¦•åŸºè½¯ä»¶è‚¡ä»½æœ‰é™å…¬å¸

[56085 rows x 4 columns]
----


+*In[33]:*+
[source, ipython3]
----
df2.to_excel(r'/Users/jiang/Library/Mobile Documents/com~apple~CloudDocs/Desktop/OneDrive - HKUST Connect/Research/Smart City/Data/df2.xlsx', index=False)
----


+*In[34]:*+
[source, ipython3]
----
from pandas import DataFrame
----


+*In[74]:*+
[source, ipython3]
----
df3 = DataFrame(df['å¸‚1'])
df3.columns=list('å¸‚')
print(df3)
----


+*Out[74]:*+
----
         å¸‚
0      NaN
1      æ´›é˜³å¸‚
2      éƒ‘å·å¸‚
3      å®‰é˜³å¸‚
4      NaN
...    ...
56080  å•†ä¸˜å¸‚
56081  NaN
56082  NaN
56083  å•†ä¸˜å¸‚
56084  NaN

[56085 rows x 1 columns]
----


+*In[75]:*+
[source, ipython3]
----
df4 = DataFrame(df['å¸‚2'])
df4.columns=list('å¸‚')
print(df4)
----


+*Out[75]:*+
----
         å¸‚
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
56080  åŒ—äº¬å¸‚
56081  ä¸Šæµ·å¸‚
56082  NaN
56083  NaN
56084  NaN

[56085 rows x 1 columns]
----


+*In[76]:*+
[source, ipython3]
----

result = df3.combine_first(df4)
----


+*In[77]:*+
[source, ipython3]
----
print(result)
----


+*Out[77]:*+
----
         å¸‚
0      NaN
1      æ´›é˜³å¸‚
2      éƒ‘å·å¸‚
3      å®‰é˜³å¸‚
4      NaN
...    ...
56080  å•†ä¸˜å¸‚
56081  ä¸Šæµ·å¸‚
56082  NaN
56083  å•†ä¸˜å¸‚
56084  NaN

[56085 rows x 1 columns]
----


+*In[43]:*+
[source, ipython3]
----
df.dtypes == 'object'
----


+*Out[43]:*+
----c1              False
order_number    False
ä¸­æ ‡æ ‡é¢˜             True
industry         True
å…³é”®è¯              True
åœ°åŒº               True
å¸‚2               True
å¸‚1               True
é‡‡è´­å•ä½             True
organization     True
å¹´ä»½              False
link             True
ä»£ç†å…¬å¸             True
æ—¥æœŸ               True
ä¸­æ ‡é‡‘é¢            False
ä¸­æ ‡å•ä½             True
dtype: bool----


+*In[47]:*+
[source, ipython3]
----
num_vars = df.columns[df.dtypes != 'object']
----


+*In[46]:*+
[source, ipython3]
----
cat_vars = df.columns[df.dtypes == 'object']
----


+*In[52]:*+
[source, ipython3]
----
df1['å¸‚'].isnull().sum()
----


+*Out[52]:*+
----0----


+*In[53]:*+
[source, ipython3]
----
df1.dtypes == 'object'
----


+*Out[53]:*+
----çœ     True
å¸‚     True
åŒº     True
åœ°å€    True
dtype: bool----


+*In[54]:*+
[source, ipython3]
----
df1.to_excel(r'/Users/jiang/Library/Mobile Documents/com~apple~CloudDocs/Desktop/OneDrive - HKUST Connect/Research/Smart City/Data/df1.xlsx', index=False)
----


+*In[57]:*+
[source, ipython3]
----
df3['å¸‚1'].isnull().sum()
----


+*Out[57]:*+
----15342----


+*In[61]:*+
[source, ipython3]
----
df4['å¸‚2'].isnull().sum()
----


+*Out[61]:*+
----27165----


+*In[78]:*+
[source, ipython3]
----
result.isnull().sum()
----


+*Out[78]:*+
----å¸‚    7659
dtype: int64----


+*In[79]:*+
[source, ipython3]
----
result.to_excel(r'/Users/jiang/Library/Mobile Documents/com~apple~CloudDocs/Desktop/OneDrive - HKUST Connect/Research/Smart City/Data/result.xlsx', index=False)
----


+*In[ ]:*+
[source, ipython3]
----

----
